"""
Script to seed the database with internship data.
Run: python seed_data.py
"""
from app.db import SessionLocal, engine
from app.models import Base, Internship

Base.metadata.create_all(bind=engine)


def seed_internships():
    db = SessionLocal()

    existing = db.query(Internship).first()
    if existing:
        print("Data already exists. Skipping seed.")
        db.close()
        return

    internships = [
        # ── IT ───────────────────────────────────────────────────────────────
        Internship(
            category='IT',
            title='Junior Flutter Developer',
            company='TechNova',
            city='Астана',
            format='Hybrid',
            paid=True, salary_kzt=150000, duration='3 месяца',
            description='Разработка мобильного приложения на Flutter. Реальные задачи в команде из 5 человек. Менторство от senior-разработчика.',
            responsibilities=['Собирать UI экраны по макетам в Figma', 'Подключать REST API', 'Участвовать в code review', 'Исправлять баги и улучшать производительность'],
            requirements=['Базовый Dart / Flutter', 'Понимание навигации и состояния', 'Git на базовом уровне'],
            skills=['Flutter', 'Dart', 'REST API', 'Git', 'Material 3'],
            contact_email='hr@technova.kz', tags=['mobile', 'flutter', 'ui'],
        ),
        Internship(
            category='IT',
            title='Frontend Intern (React)',
            company='Digital Hub KZ',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=130000, duration='2 месяца',
            description='Разработка веб-интерфейсов для корпоративных клиентов. Работаешь с настоящим дизайном и реальными пользователями.',
            responsibilities=['Верстать компоненты по дизайн-системе', 'Интегрировать GraphQL API', 'Писать unit-тесты на Jest', 'Участвовать в daily standups'],
            requirements=['HTML, CSS, JS уверенно', 'Базовый React (hooks)', 'Понимание адаптивной вёрстки'],
            skills=['React', 'TypeScript', 'GraphQL', 'Jest', 'Figma'],
            contact_email='jobs@digitalhub.kz', tags=['frontend', 'react', 'web'],
        ),
        Internship(
            category='IT',
            title='Backend Intern (Python/FastAPI)',
            company='BuildKZ',
            city='Шымкент',
            format='Remote',
            paid=False, salary_kzt=None, duration='1–2 месяца',
            description='Помощь с backend на FastAPI: роуты, схемы, интеграция с БД. Хорошая возможность для старта карьеры в backend.',
            responsibilities=['Создавать API эндпоинты', 'Писать Pydantic схемы', 'Работать с PostgreSQL через SQLAlchemy', 'Покрывать код тестами'],
            requirements=['Python базовый', 'Понимание REST', 'Желание учиться'],
            skills=['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Git'],
            contact_email='team@buildkz.kz', tags=['backend', 'python', 'api'],
        ),
        Internship(
            category='IT',
            title='iOS Developer Intern',
            company='AppFactory',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=170000, duration='3 месяца',
            description='Разработка нативных iOS приложений для финтех-стартапа. Работаешь с Swift 5.9, SwiftUI и Combine.',
            responsibilities=['Разрабатывать новые фичи в SwiftUI', 'Оптимизировать производительность', 'Писать unit и UI тесты', 'Работать по Agile/Scrum'],
            requirements=['Swift базовый', 'Понимание UIKit или SwiftUI', 'Xcode'],
            skills=['Swift', 'SwiftUI', 'UIKit', 'Combine', 'Xcode'],
            contact_email='ios@appfactory.kz', tags=['ios', 'swift', 'mobile'],
        ),
        Internship(
            category='IT',
            title='DevOps Intern',
            company='CloudStep',
            city='Астана',
            format='Remote',
            paid=True, salary_kzt=140000, duration='2 месяца',
            description='Настройка CI/CD пайплайнов, мониторинг сервисов, работа с Kubernetes. Реальная инфраструктура.',
            responsibilities=['Поддерживать CI/CD пайплайны на GitHub Actions', 'Настраивать мониторинг (Prometheus + Grafana)', 'Работать с Docker и Kubernetes', 'Документировать инфраструктуру'],
            requirements=['Linux базово', 'Docker понимание', 'Любой скриптовый язык'],
            skills=['Docker', 'Kubernetes', 'CI/CD', 'Linux', 'Bash', 'Prometheus'],
            contact_email='devops@cloudstep.kz', tags=['devops', 'cloud', 'infrastructure'],
        ),
        Internship(
            category='IT',
            title='QA Engineer Intern',
            company='TestLab KZ',
            city='Алматы',
            format='Hybrid',
            paid=True, salary_kzt=110000, duration='2–3 месяца',
            description='Тестирование веб и мобильных приложений. Написание тест-кейсов, автотесты на Python/Selenium.',
            responsibilities=['Составлять тест-планы и тест-кейсы', 'Проводить ручное и регрессионное тестирование', 'Писать автотесты на Selenium', 'Вести баг-репорты в Jira'],
            requirements=['Понимание SDLC и STLC', 'Базовый Python или JS', 'Внимание к деталям'],
            skills=['Selenium', 'Python', 'Jira', 'Postman', 'SQL'],
            contact_email='qa@testlab.kz', tags=['qa', 'testing', 'automation'],
        ),
        Internship(
            category='IT',
            title='Data Science Intern',
            company='DataWave',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=160000, duration='3 месяца',
            description='Работа с реальными датасетами: классификация, кластеризация, визуализация. Менторство от DS-team.',
            responsibilities=['Очищать и подготавливать данные', 'Строить ML модели (sklearn)', 'Визуализировать результаты', 'Писать отчёты о находках'],
            requirements=['Python (pandas, numpy)', 'Базовая статистика', 'Jupyter Notebook'],
            skills=['Python', 'Pandas', 'Scikit-learn', 'Matplotlib', 'SQL'],
            contact_email='ds@datawave.kz', tags=['data science', 'ml', 'python'],
        ),
        Internship(
            category='IT',
            title='Machine Learning Intern',
            company='AICore KZ',
            city='Астана',
            format='Hybrid',
            paid=True, salary_kzt=200000, duration='3–4 месяца',
            description='Разработка и обучение моделей компьютерного зрения для промышленного применения.',
            responsibilities=['Собирать и размечать датасеты', 'Обучать CNN и трансформеры', 'Оптимизировать модели для edge-девайсов', 'Писать inference пайплайны'],
            requirements=['PyTorch или TensorFlow', 'Линейная алгебра', 'Python продвинутый'],
            skills=['PyTorch', 'OpenCV', 'Python', 'ONNX', 'Git'],
            contact_email='ml@aicore.kz', tags=['ml', 'ai', 'cv', 'deep learning'],
        ),
        Internship(
            category='IT',
            title='Android Intern (Kotlin)',
            company='MobileFirst',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=145000, duration='2 месяца',
            description='Разработка нового модуля в уже живом приложении с 50 000+ пользователей.',
            responsibilities=['Писать Kotlin код по архитектуре MVVM', 'Работать с Retrofit и Coroutines', 'Писать unit-тесты', 'Делать code review'],
            requirements=['Kotlin базовый', 'Android Studio', 'ООП понимание'],
            skills=['Kotlin', 'Android', 'MVVM', 'Retrofit', 'Coroutines'],
            contact_email='android@mobilefirst.kz', tags=['android', 'kotlin', 'mobile'],
        ),
        Internship(
            category='IT',
            title='Cybersecurity Intern',
            company='SecureNet KZ',
            city='Астана',
            format='On-site',
            paid=True, salary_kzt=155000, duration='3 месяца',
            description='Анализ уязвимостей, пентест корпоративных систем, работа с SIEM-системами.',
            responsibilities=['Проводить vulnerability assessment', 'Анализировать логи в SIEM', 'Документировать результаты', 'Участвовать в инцидент-менеджменте'],
            requirements=['Сети (TCP/IP)', 'Linux базово', 'Понимание OWASP Top 10'],
            skills=['Kali Linux', 'Burp Suite', 'Wireshark', 'Python', 'Nmap'],
            contact_email='security@securenet.kz', tags=['security', 'pentest', 'linux'],
        ),

        # ── Финансы ──────────────────────────────────────────────────────────
        Internship(
            category='Финансы',
            title='Data Analyst Intern',
            company='FinPulse',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=120000, duration='2–3 месяца',
            description='Аналитическая стажировка в финтех-компании. Отчёты, SQL, BI дашборды. Реальные задачи.',
            responsibilities=['Собирать данные из источников', 'Писать SQL запросы', 'Строить дашборды в Power BI', 'Делать презентации для менеджмента'],
            requirements=['Excel/Google Sheets уверенно', 'Базовый SQL', 'Внимание к деталям'],
            skills=['SQL', 'Excel', 'Power BI', 'Python'],
            contact_email='interns@finpulse.kz', tags=['analytics', 'sql', 'bi', 'finance'],
        ),
        Internship(
            category='Финансы',
            title='Финансовый аналитик (стажёр)',
            company='Halyk Invest',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=135000, duration='3 месяца',
            description='Работа с финансовой отчётностью, моделирование, анализ инвестиционных проектов.',
            responsibilities=['Анализировать финансовую отчётность компаний', 'Строить финансовые модели в Excel', 'Готовить инвестиционные меморандумы', 'Мониторить рынок'],
            requirements=['Финансы или экономика (2–4 курс)', 'Excel продвинутый', 'Английский B1+'],
            skills=['Excel', 'Финансовое моделирование', 'Bloomberg', 'PowerPoint'],
            contact_email='careers@halyk-invest.kz', tags=['finance', 'investment', 'excel'],
        ),
        Internship(
            category='Финансы',
            title='Intern Бухгалтер',
            company='AuditPro',
            city='Астана',
            format='On-site',
            paid=False, salary_kzt=None, duration='1 месяц',
            description='Практика по бухгалтерскому учёту и аудиту. Отлично подходит для студентов специальности "Учёт и аудит".',
            responsibilities=['Вводить первичные документы в 1С', 'Помогать с составлением отчётности', 'Сверять данные', 'Архивировать документы'],
            requirements=['Знание 1С базово', 'Учёт или экономика', 'Аккуратность'],
            skills=['1С', 'Excel', 'Бухучёт', 'МСФО основы'],
            contact_email='hr@auditpro.kz', tags=['accounting', '1c', 'audit'],
        ),
        Internship(
            category='Финансы',
            title='Risk Analyst Intern',
            company='Kaspi Bank',
            city='Алматы',
            format='Hybrid',
            paid=True, salary_kzt=180000, duration='3 месяца',
            description='Анализ кредитных рисков, работа с большими данными, скоринговые модели.',
            responsibilities=['Анализировать кредитные портфели', 'Работать со скоринговыми моделями', 'Готовить риск-отчёты', 'Автоматизировать аналитику в Python'],
            requirements=['Python или R', 'Статистика', 'Финансы или математика'],
            skills=['Python', 'SQL', 'SAS', 'Excel', 'Статистика'],
            contact_email='risk.intern@kaspi.kz', tags=['risk', 'banking', 'data', 'finance'],
        ),
        Internship(
            category='Финансы',
            title='Treasury Intern',
            company='Freedom Finance',
            city='Астана',
            format='On-site',
            paid=True, salary_kzt=125000, duration='2 месяца',
            description='Работа с казначейскими операциями, валютный рынок, ликвидность.',
            responsibilities=['Мониторить валютные позиции', 'Готовить ежедневные отчёты', 'Работать с Reuters/Bloomberg', 'Помогать в исполнении сделок'],
            requirements=['Финансы/экономика', 'Английский B2', 'Excel уверенно'],
            skills=['Bloomberg', 'Excel', 'FX рынок', 'Финансовый анализ'],
            contact_email='treasury@ffin.kz', tags=['treasury', 'forex', 'banking'],
        ),

        # ── Дизайн ───────────────────────────────────────────────────────────
        Internship(
            category='Дизайн',
            title='UI/UX Designer Intern',
            company='PixelCraft',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=100000, duration='2 месяца',
            description='Проектирование экранов для мобильных приложений. Работаешь с дизайн-системой и реальными пользователями.',
            responsibilities=['Создавать wireframes и прототипы в Figma', 'Проводить usability тесты', 'Поддерживать дизайн-систему', 'Работать с командой разработки'],
            requirements=['Figma уверенно', 'Портфолио (хотя бы учебные проекты)', 'Понимание UX принципов'],
            skills=['Figma', 'Prototyping', 'User Research', 'Design Systems'],
            contact_email='design@pixelcraft.kz', tags=['design', 'ui', 'ux', 'figma'],
        ),
        Internship(
            category='Дизайн',
            title='Graphic Designer Intern',
            company='BrandStudio',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=90000, duration='2 месяца',
            description='Разработка визуальных материалов для клиентов: бренды, упаковка, рекламные макеты.',
            responsibilities=['Создавать брендинг материалы', 'Разрабатывать макеты для печати и digital', 'Готовить презентации', 'Работать с клиентскими брифами'],
            requirements=['Adobe Illustrator, Photoshop', 'Портфолио', 'Понимание типографики'],
            skills=['Adobe Illustrator', 'Photoshop', 'InDesign', 'Figma'],
            contact_email='hr@brandstudio.kz', tags=['graphic design', 'branding', 'adobe'],
        ),
        Internship(
            category='Дизайн',
            title='Motion Designer Intern',
            company='VideoLab',
            city='Астана',
            format='Remote',
            paid=True, salary_kzt=110000, duration='2–3 месяца',
            description='Создание анимированного контента для соцсетей, рекламы и продуктовых презентаций.',
            responsibilities=['Делать анимации в After Effects', 'Создавать reels и short-video контент', 'Анимировать UI элементы', 'Работать с дизайн командой'],
            requirements=['After Effects базово', 'Понимание принципов анимации', 'Портфолио'],
            skills=['After Effects', 'Premiere Pro', 'Figma', 'Lottie'],
            contact_email='motion@videolab.kz', tags=['motion', 'animation', 'video'],
        ),
        Internship(
            category='Дизайн',
            title='Product Designer Intern',
            company='StartupHub',
            city='Алматы',
            format='Hybrid',
            paid=True, salary_kzt=130000, duration='3 месяца',
            description='Работа над продуктом от исследования до финального дизайна. Полный цикл в стартапе.',
            responsibilities=['Проводить user research и интервью', 'Создавать user flows и прототипы', 'Тестировать дизайн решения', 'Работать вместе с PM и dev командой'],
            requirements=['Figma или Sketch', 'Интерес к продуктовому мышлению', 'Английский B1+'],
            skills=['Figma', 'User Research', 'Prototyping', 'Notion', 'Miro'],
            contact_email='product@startuphub.kz', tags=['product design', 'ux research', 'startup'],
        ),

        # ── Маркетинг ────────────────────────────────────────────────────────
        Internship(
            category='Маркетинг',
            title='SMM Intern',
            company='Social Boost',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=80000, duration='2 месяца',
            description='Ведение Instagram, TikTok и LinkedIn для брендов. Создание контента, аналитика.',
            responsibilities=['Создавать контент-план на месяц', 'Писать тексты и подписи к постам', 'Анализировать статистику аккаунтов', 'Предлагать идеи для роста'],
            requirements=['Понимание алгоритмов соцсетей', 'Грамотный русский/казахский', 'Canva или Adobe'],
            skills=['Instagram', 'TikTok', 'Canva', 'Копирайтинг', 'Аналитика'],
            contact_email='smm@socialboost.kz', tags=['smm', 'social media', 'content'],
        ),
        Internship(
            category='Маркетинг',
            title='SEO Intern',
            company='RankUp KZ',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=95000, duration='2 месяца',
            description='Оптимизация сайтов под поисковые системы. Семантика, on-page, аналитика трафика.',
            responsibilities=['Собирать семантическое ядро', 'Анализировать конкурентов', 'Оптимизировать мета-теги и контент', 'Работать с Google Search Console'],
            requirements=['Базовое понимание SEO', 'Аналитическое мышление', 'Excel'],
            skills=['Google Search Console', 'Ahrefs', 'Screaming Frog', 'Excel', 'SEMrush'],
            contact_email='seo@rankup.kz', tags=['seo', 'digital marketing', 'analytics'],
        ),
        Internship(
            category='Маркетинг',
            title='Content Marketing Intern',
            company='MediaPro',
            city='Астана',
            format='Hybrid',
            paid=True, salary_kzt=85000, duration='2 месяца',
            description='Написание статей, кейсов и email-рассылок для B2B компании. Реальная аудитория с первого дня.',
            responsibilities=['Писать статьи для блога (4+ в месяц)', 'Готовить email-рассылки', 'Создавать кейсы на основе интервью', 'Работать с SEO-требованиями'],
            requirements=['Грамотный русский', 'Умение писать структурно', 'Базовый SEO'],
            skills=['Копирайтинг', 'SEO', 'Email Marketing', 'Notion', 'Tilda'],
            contact_email='content@mediapro.kz', tags=['content', 'copywriting', 'email'],
        ),
        Internship(
            category='Маркетинг',
            title='Performance Marketing Intern',
            company='AdScale',
            city='Алматы',
            format='Remote',
            paid=True, salary_kzt=100000, duration='2 месяца',
            description='Настройка и оптимизация рекламных кампаний в Google Ads, Meta, TikTok для e-commerce клиентов.',
            responsibilities=['Запускать рекламные кампании', 'Анализировать CPС, CPL, ROAS', 'A/B тестировать креативы', 'Готовить еженедельные отчёты'],
            requirements=['Понимание таргета и контекста', 'Аналитический склад', 'Excel'],
            skills=['Google Ads', 'Meta Ads', 'TikTok Ads', 'Analytics', 'Excel'],
            contact_email='perf@adscale.kz', tags=['performance', 'google ads', 'targeting'],
        ),
        Internship(
            category='Маркетинг',
            title='Brand Manager Intern',
            company='Technodom',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=115000, duration='3 месяца',
            description='Участие в разработке и продвижении бренда одной из крупнейших розничных сетей Казахстана.',
            responsibilities=['Помогать в разработке брендовых материалов', 'Координировать подрядчиков', 'Анализировать конкурентов', 'Участвовать в маркетинговых акциях'],
            requirements=['Маркетинг или коммуникации', 'Английский B2', 'Excel уверенно'],
            skills=['Brand Management', 'Excel', 'PowerPoint', 'Market Research'],
            contact_email='brand@technodom.kz', tags=['brand', 'retail', 'marketing'],
        ),

        # ── HR ───────────────────────────────────────────────────────────────
        Internship(
            category='HR',
            title='HR Recruiter Intern',
            company='TalentHub',
            city='Алматы',
            format='Hybrid',
            paid=True, salary_kzt=90000, duration='2 месяца',
            description='Подбор IT специалистов: поиск, скрининг, координация интервью. Работаешь с реальными вакансиями.',
            responsibilities=['Размещать вакансии на платформах', 'Проводить первичный скрининг резюме', 'Организовывать интервью', 'Вести базу кандидатов в ATS'],
            requirements=['Коммуникабельность', 'Интерес к HR', 'Английский B1'],
            skills=['LinkedIn Recruiter', 'HH.kz', 'Интервьюирование', 'ATS системы'],
            contact_email='recruit@talenthub.kz', tags=['hr', 'recruiting', 'talent'],
        ),
        Internship(
            category='HR',
            title='HR Business Partner Intern',
            company='Kolesa Group',
            city='Алматы',
            format='On-site',
            paid=True, salary_kzt=100000, duration='3 месяца',
            description='Стажировка в HR команде крупной IT-компании. Адаптация, онбординг, корпоративная культура.',
            responsibilities=['Помогать в онбординге новых сотрудников', 'Организовывать корпоративные события', 'Проводить опросы вовлечённости', 'Готовить HR аналитику'],
            requirements=['Психология, управление персоналом или смежное', 'Эмпатия', 'Excel'],
            skills=['HR Analytics', 'Excel', 'Опросы', 'Коммуникация'],
            contact_email='hr@kolesa.kz', tags=['hr', 'people ops', 'culture'],
        ),
        Internship(
            category='HR',
            title='L&D Intern (обучение и развитие)',
            company='Beeline KZ',
            city='Астана',
            format='On-site',
            paid=True, salary_kzt=105000, duration='2–3 месяца',
            description='Разработка учебных программ и тренингов для сотрудников крупной телеком-компании.',
            responsibilities=['Помогать разрабатывать обучающие материалы', 'Организовывать тренинги', 'Анализировать эффективность обучения', 'Работать с LMS системой'],
            requirements=['Педагогика, психология или HR', 'Навыки презентации', 'PowerPoint'],
            skills=['Instructional Design', 'LMS', 'PowerPoint', 'Facilitation'],
            contact_email='learning@beeline.kz', tags=['hr', 'learning', 'training', 'lms'],
        ),
    ]

    for internship in internships:
        db.add(internship)

    db.commit()
    print(f"Successfully added {len(internships)} internships!")
    db.close()


if __name__ == "__main__":
    seed_internships()
